services:

  caddy:
    image: caddy:2
    container_name: caddy
    restart: unless-stopped
    depends_on:
      - webtop
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
    env_file:
      - .env
    environment:
      - ACME_AGREE=true
      - EMAIL=${EMAIL}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config

  webtop:
    build: .
    container_name: webtop
    restart: unless-stopped
    shm_size: "2gb"
    ports:
      - "${WEBTOP_LOCAL_PORT:-3000}:3000"
      - "${WEBTOP_LOCAL_HTTPS_PORT:-3001}:3001"
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TITLE=${TITLE:-Webtop Recorder}
    volumes:
      - ./home:/config
    security_opt:
      - label=disable

volumes:
  caddy_data:
  caddy_config:
